version: '3.8'

services:
  nodebb:
    build: .
    # image: ghcr.io/nodebb/nodebb:latest
    # image: teacher_forum
    restart: unless-stopped
    ports:
      - '4567:4567' # comment this out if you don't want to expose NodeBB to the host, or change the first number to any port you want
    volumes:
      - nodebb-uploads:/usr/src/app/public/uploads
      - ./install/docker:/usr/src/app/install/docker
    environment:
      NODEBB_URL: "http://localhost:4567"
      NODEBB_SECRET: "d1cbf07a-21e5-4806-bf7d-aae99b9a0946"
      NODEBB_DATABASE: "postgres"
      NODEBB_DB_HOST: "localhost"
      NODEBB_DB_PORT: "5432"
      NODEBB_DB_USER: "postgres"
      NODEBB_DB_PASSWORD: "W3Fc4Ab"
      NODEBB_DB_NAME: "forum"
      NODEBB_DB_SSL: "false"
      NODEBB_PORT: "4567"
    network_mode: "host"

      
# {
#           "url": "http://localhost:4567",
#           "secret": "d1cbf07a-21e5-4806-bf7d-aae99b9a0946",
#           "database": "postgres",
#           "postgres": {
#               "host": "127.0.0.1",
#               "port": "5432",
#               "username": "postgres",
#               "password": "W3Fc4Ab",
#               "database": "forum",
#               "ssl": "false"
#           },
#           "port": "4567"
#       }

volumes:
  # nodebb-build:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ./.docker/build

  nodebb-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/public/uploads

  # nodebb-config:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ./.docker/config
